[package]
authors = ["Enrico Risa <enrico.risa@gmail.com>"]
name = "gremlin-client"
version = "0.3.0"
edition = "2018"
license = "Apache-2.0"
description= "A Rust client for Apache TinkerPopâ„¢"
repository = "https://github.com/wolf4ood/gremlin-rs"
keywords = ["database", "graphs","tinkerpop"]
categories = ["database"]
readme = "README.md"



[features]

default = []



async_gremlin = ["futures"]

async_std = ["async_gremlin","async-std","async-tungstenite","async-trait","mobc","url","async-tls","pin-project-lite"]

 

[badges]
travis-ci = { repository = "wolf4ood/gremlin-rs" }
codecov = { repository = "wolf4ood/gremlin-rs", branch = "master", service = "github" }
is-it-maintained-issue-resolution = { repository = "wolf4ood/gremlin-rs" }
is-it-maintained-open-issues = { repository = "wolf4ood/gremlin-rs" }
maintenance = {status = "actively-developed"}

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive="1.0"
r2d2 = "0.8.3"
chrono = "0.4"
lazy_static = "1.3.0"
base64 = "0.11.0"
native-tls = "0.2.3"
async-tungstenite = { version = "0.2.1", optional = true }
async-std =  { version = "1.2.0", optional = true, features = ["unstable"] }
async-trait = { version = "0.1.10", optional = true }
async-tls =  { version = "0.6.0", optional = true }
mobc = {  default-features = false, version = "0.2.8", optional = true, features = ["async-std-runtime"] }
url =  {version = "2.1.0", optional = true}
futures = { version = "0.3.1", optional = true}
pin-project-lite = { version = "0.1.1", optional = true}



[dependencies.websocket]
version="0.24"
default-features = false 
features = ["sync","sync-ssl"]

[dependencies.uuid]
features = ["serde", "v4"]
version = "0.7.2"



[[test]]
name = "integration_client_async"
required-features = ["async_std"]

[[test]]
name = "integration_traversal_async"
required-features = ["async_std"]

[[test]]
name = "common_async"
required-features = ["async_std"]


[[example]]
name = "traversal_async"
required-features = ["async_std"]