[package]
authors = ["Enrico Risa <enrico.risa@gmail.com>"]
name = "gremlin-client"
version = "0.1.1"
edition = "2018"
license = "Apache-2.0"
description= "A Rust client for Apache TinkerPopâ„¢"
repository = "https://github.com/wolf4ood/gremlin-rs"
keywords = ["database", "graphs","tinkerpop"]
categories = ["database"]
readme = "README.md"



[badges]
travis-ci = { repository = "wolf4ood/gremlin-rs" }
codecov = { repository = "wolf4ood/gremlin-rs", branch = "master", service = "github" }
is-it-maintained-issue-resolution = { repository = "wolf4ood/gremlin-rs" }
is-it-maintained-open-issues = { repository = "wolf4ood/gremlin-rs" }
maintenance = {status = "actively-developed"}

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive="1.0"
r2d2 = "0.8.3"
chrono = "0.4"



[dependencies.websocket]
version="0.22"
default-features = false 
features = ["sync","sync-ssl"]

[dependencies.uuid]
features = ["serde", "v4"]
version = "0.7.2"