[package]
name = "gremlin-tutorial"
version = "0.1.0"
authors = ["wolf4ood <enrico.risa@gmail.com>"]
edition = "2018"

[dependencies]
gremlin-client = { path = "../gremlin-client", version = "0.3.0" }
